name: Java CI on Windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  MAVEN_OPTS: "-Xmx1g"

jobs:
  setup:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

  test:
    needs: setup
    runs-on: windows-latest
    strategy:
      matrix:
        java: [11, 17]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Run Tests
        run: mvn test
        shell: pwsh

  lint:
    needs: setup
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint Code
        run: .\scripts\lint.ps1
        shell: pwsh
        continue-on-error: true

  deploy:
    needs: [test, lint]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: windows-latest
    steps:
      - name: Deploy to Production
        run: .\scripts\deploy.ps1
        shell: pwsh
