name: Control Flow Example

on:
  push:
    branches:
      - master
  pull_request:

env:
  GLOBAL_ENV: "I am accessible everywhere"

jobs:
  setup:
    name: Setup Job
    runs-on: windows-latest
    outputs:
      should-run-next: ${{ steps.check.outputs.continue }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check whether to continue
        id: check
        run: |
          echo "continue=true" >> $GITHUB_OUTPUT

  build:
    name: Conditional Build Job
    needs: setup
    if: needs.setup.outputs.should-run-next == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Echo environment variable
        run: echo "GLOBAL_ENV is $GLOBAL_ENV"

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install

  test:
    name: Matrix Test Job
    needs: build
    runs-on: windows-latest
    strategy:
      matrix:
        java: [8, 11, 17]
    steps:
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Run Tests
        run: mvn test

  notify:
    name: Notify on Success
    needs: [test]
    if: ${{ success() }}
    runs-on: windows-latest
    steps:
      - name: Send success message
        run: echo "✅ All jobs completed successfully!"

