name: Java Build with Ant (Windows).

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Verify Ant is installed
        run: ant -version
        shell: cmd
      
      - name: Print files in project
        run: dir /s
        shell: cmd

      - name: Build with Ant (verbose)
        run: ant -verbose
        shell: cmd


      - name: Run Tests (if you have test target)
        run: ant test
        shell: cmd
        continue-on-error: true
