name: Java Build with Ant (Windows).

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Verify Ant is installed
        run: ant -version
        shell: cmd

      - name: Download MySQL Connector/J
        run: |
          mkdir -p lib
          curl -L -o lib/mysql-connector-j-9.2.0.jar https://repo1.maven.org/maven2/com/mysql/mysql-connector-j/9.2.0/mysql-connector-j-9.2.0.jar

      
      - name: Print files in project
        run: dir /s
        shell: cmd

      - name: Build with Ant (verbose)
        run: ant -verbose
        shell: cmd


      - name: Run Tests (if you have test target)
        run: ant test
        shell: cmd
        continue-on-error: true
